project_id = "miixzsgabxqhiqiqkpry"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-tracking-notification]
verify_jwt = false

[functions.send-visa-notification]
verify_jwt = false

[functions.send-welcome-notification]
verify_jwt = false

[functions.create-guest-account]
verify_jwt = false

[functions.payment-sslcommerz]
verify_jwt = false

[functions.payment-bkash]
verify_jwt = false

[functions.payment-nagad]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false
