project_id = "miixzsgabxqhiqiqkpry"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-tracking-notification]
verify_jwt = false

[functions.send-visa-notification]
verify_jwt = false

[functions.send-welcome-notification]
verify_jwt = false

[functions.create-guest-account]
verify_jwt = false

[functions.payment-sslcommerz]
verify_jwt = false

[functions.payment-bkash]
verify_jwt = false

[functions.payment-nagad]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false

[functions.fb-event]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.create-demo-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.send-air-ticket-notification]
verify_jwt = false

[functions.send-whatsapp-test]
verify_jwt = false

[functions.emi-reminder]
verify_jwt = false

[functions.payment-installment]
verify_jwt = false

[functions.send-emi-notification]
verify_jwt = false
